services:
    redis:
        image: redis:7.4
        ports:
            - "6379:6379"
        networks:
            - f1race

    node:
        image: node:22-bullseye-slim
        volumes:
            - ./:/var/www
        working_dir: /var/www/
        depends_on:
            - redis
        networks:
            - f1race

networks:
    f1race:
